Integrate manifest-tool push in build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -22,10 +22,26 @@ if [[ ! ${DOCKER_ARCH} ]]; then
 fi
 
 for VERSION in ${VERSIONS}; do
-  TAG="${DOCKER_USER}/${DOCKER_IMAGE}:${DOCKER_ARCH}-${VERSION}"
-  echo "Building ${DOCKER_ARCH}.."
-  docker build -t ${TAG} -f Dockerfile.${VERSION} .
-  [[ "$NO_PUSH" ]] || docker push ${TAG}
+	TAG="${DOCKER_USER}/${DOCKER_IMAGE}:${DOCKER_ARCH}-${VERSION}"
+	echo "Building ${DOCKER_ARCH}.."
+	docker build -t ${TAG} -f Dockerfile.${VERSION} .
 done
+
 docker tag ${DOCKER_USER}/${DOCKER_IMAGE}:${DOCKER_ARCH}-1.9.1 ${DOCKER_USER}/${DOCKER_IMAGE}:${DOCKER_ARCH}
-[[ "${NO_PUSH}" ]] || docker push ${DOCKER_USER}/${DOCKER_IMAGE}:${DOCKER_ARCH}
+
+if [[ ! "${NO_PUSH}" ]]; then
+	echo "Pushing images.."
+	for VERSION in ${VERSIONS}; do
+		docker push ${TAG}
+	done
+	docker push ${DOCKER_USER}/${DOCKER_IMAGE}:${DOCKER_ARCH}
+fi
+
+if ! which manifest-tool 1>/dev/null; then
+	echo "FATAL: No manifest-tool found on PATH, can't push multi-arch manifests." >&2
+	exit 1
+fi
+echo "Pushing multi-arch manifests.."
+for VERSION in ${VERSIONS}; do
+	manifest-tool push from-args --platforms linux/amd64,linux/arm --template hkjn/golang:ARCH-${VERSION} --target hkjn/golang:${VERSION}
+done
